version: '3.1'

services:
  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./backend/:/home/user/app/
      - ./webpack-stats.json:/home/user/webpack-stats.json
    env_file: backend/.env
